version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 20
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build --configuration production --aot
  post_build:
     commands:
      - aws s3 cp dist/portafolio-angular/browser s3://aejim-portafolio-front --recursive
      - echo Build completed on `date`  
artifacts:  
    files:
        - '**/*'
    base-directory: 'dist/portafolio-angular/browser*'
    discard-paths: yes