/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'on-error': '#690005',
        'on-tertiary-fixed-variant': '#723600',
        'surface-container-low': '#0d1c2d',
        'inverse-on-surface': '#233143',
        'secondary': '#bcc7de',
        'primary-fixed': '#d8e2ff',
        'on-primary': '#002e6a',
        'surface-bright': '#2c3a4c',
        'on-secondary': '#263143',
        'on-surface': '#d4e4fa',
        'secondary-fixed-dim': '#bcc7de',
        'inverse-surface': '#d4e4fa',
        'secondary-fixed': '#d8e3fb',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#3c475a',
        'tertiary-container': '#df7412',
        'tertiary-fixed-dim': '#ffb786',
        'surface-container': '#122131',
        'surface': '#051424',
        'surface-container-high': '#1c2b3c',
        'primary': '#adc6ff',
        'surface-variant': '#273647',
        'outline': '#8c909f',
        'on-background': '#d4e4fa',
        'error': '#ffb4ab',
        'on-tertiary-fixed': '#311400',
        'error-container': '#93000a',
        'primary-fixed-dim': '#adc6ff',
        'on-secondary-fixed': '#111c2d',
        'on-primary-fixed': '#001a42',
        'surface-container-lowest': '#010f1f',
        'on-tertiary': '#502400',
        'background': '#051424',
        'primary-container': '#4d8eff',
        'outline-variant': '#424754',
        'on-primary-fixed-variant': '#004395',
        'inverse-primary': '#005ac2',
        'on-tertiary-container': '#461f00',
        'surface-dim': '#051424',
        'on-secondary-container': '#aeb9d0',
        'tertiary-fixed': '#ffdcc6',
        'secondary-container': '#3e495d',
        'surface-tint': '#adc6ff',
        'surface-container-highest': '#273647',
        'on-surface-variant': '#c2c6d6',
        'on-primary-container': '#00285d',
        'tertiary': '#ffb786',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'container-max': '1200px',
        'base': '4px',
        'xs': '8px',
        'sm': '16px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        'display-lg': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'body-sm': ['Geist', 'sans-serif'],
        'label-caps': ['Geist', 'sans-serif'],
        'mono-data': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-data': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
